/**
 * PiLabs API
 * Generated by nestia - https://github.com/samchon/nestia
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PluginInfo { 
    description: string;
    version: string;
    name: string;
    id: string;
    url: string;
    isInstalled: boolean;
}

