/**
 * PiLabs API
 * Generated by nestia - https://github.com/samchon/nestia
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Options for `StreamableFile`
 */
export interface StreamableFileOptions { 
    /**
     * The value that will be used for the `Content-Type` response header.
     */
    type?: string;
    /**
     * The value that will be used for the `Content-Disposition` response header.
     */
    disposition?: string;
    /**
     * The value that will be used for the `Content-Length` response header.
     */
    length?: number;
}

